# FirstMethod

In [1]:
 import pandas as pd
from sklearn import linear_model
import numpy as np

In [2]:
df=pd.read_csv('homeprices.csv')

In [3]:
df

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [4]:
#inorder to handle the column town which is in string

In [5]:
dummies=pd.get_dummies(df.town)
dummies

monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [6]:
merged=pd.concat([df,dummies],axis=1)

In [7]:
merged

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [8]:
final=merged.drop(['town','west windsor'],axis=1)
final

area   price  monroe township  robinsville
0   2600  550000                1            0
1   3000  565000                1            0
2   3200  610000                1            0
3   3600  680000                1            0
4   4000  725000                1            0
5   2600  585000                0            0
6   2800  615000                0            0
7   3300  650000                0            0
8   3600  710000                0            0
9   2600  575000                0            1
10  2900  600000                0            1
11  3100  620000                0            1
12  3600  695000                0            1

In [9]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [10]:
x=final.drop('price',axis=1)
x

area  monroe township  robinsville
0   2600                1            0
1   3000                1            0
2   3200                1            0
3   3600                1            0
4   4000                1            0
5   2600                0            0
6   2800                0            0
7   3300                0            0
8   3600                0            0
9   2600                0            1
10  2900                0            1
11  3100                0            1
12  3600                0            1

In [11]:
y=df.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [12]:
model.fit(x,y)

LinearRegression()

In [13]:
model.coef_

array([   126.89744141, -40013.97548914, -14327.56396474])

In [14]:
model.predict([[2800,0,1]])#robinsville[0,1] because 1 is present in column(robinsvile) last and 1 is present 1st in munroe 

array([590775.63964739])

In [15]:
model.predict([[2800,0,0]])

array([605103.20361213])

In [16]:
model.predict([[2800,1,0]])#munroe

array([565089.22812299])

In [17]:
model.score(x,y)  #95% accurate

0.9573929037221873

# Using OnehotEncoder Second Method

In [132]:
df

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [133]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [134]:
dfle=df

In [135]:
le.fit_transform(dfle.town)#coverted category to label

array([0, 0, 0, 0, 0, 2, 2, 2, 2, 1, 1, 1, 1], dtype=int64)

In [136]:
dfle['town']=le.fit_transform(dfle['town'])

In [137]:
dfle

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [138]:
x=dfle[['town','area']].values
x

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]], dtype=int64)

In [139]:
y=dfle['price']
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [140]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [141]:
ct=ColumnTransformer([("town",OneHotEncoder(),[0])],remainder='passthrough')

In [142]:
x=ct.fit_transform(x.tolist())
# data= np.array(ct.fit_transform(dfle), dtype = np.str)

In [143]:
x

array([[1.0, 0.0, 0.0, 2600],
       [1.0, 0.0, 0.0, 3000],
       [1.0, 0.0, 0.0, 3200],
       [1.0, 0.0, 0.0, 3600],
       [1.0, 0.0, 0.0, 4000],
       [0.0, 0.0, 1.0, 2600],
       [0.0, 0.0, 1.0, 2800],
       [0.0, 0.0, 1.0, 3300],
       [0.0, 0.0, 1.0, 3600],
       [0.0, 1.0, 0.0, 2600],
       [0.0, 1.0, 0.0, 2900],
       [0.0, 1.0, 0.0, 3100],
       [0.0, 1.0, 0.0, 3600]], dtype=object)

In [144]:
x=x[:,1:]
x

array([[0.0, 0.0, 2600],
       [0.0, 0.0, 3000],
       [0.0, 0.0, 3200],
       [0.0, 0.0, 3600],
       [0.0, 0.0, 4000],
       [0.0, 1.0, 2600],
       [0.0, 1.0, 2800],
       [0.0, 1.0, 3300],
       [0.0, 1.0, 3600],
       [1.0, 0.0, 2600],
       [1.0, 0.0, 2900],
       [1.0, 0.0, 3100],
       [1.0, 0.0, 3600]], dtype=object)

In [145]:
model.fit(x,y)

LinearRegression()

In [146]:
model.predict([[1,0,2800]])#robinzer

array([590775.63964739])

In [147]:
model.predict([[0,1,3400]])

array([681241.6684584])

In [148]:
model.predict([[0,0,2800]])

array([565089.22812299])

In [113]:
Model=LinearRegression()
X=dfle[['town','area']].values
Y=dfle['price']
transformer = ColumnTransformer(
    transformers=[("town",OneHotEncoder(categories='auto'), [0])],remainder='passthrough' 
)
transformer.fit_transform(X.tolist())

Model.fit(X, Y)
print(model.predict([[0,2800]]))
print(model.predict([[2,3400]])) 

[567030.84084958]
[682889.14751237]
