# Disease Prediction from Symptom Updated

**Got the dataset from here**<br>
https://www.kaggle.com/itachi9604/disease-symptom-description-dataset

In [132]:
import numpy as np
import pandas as pd
from collections import defaultdict
import csv

In [133]:
raw_df=pd.read_csv('dataset.csv')
raw_df.head()

Disease   Symptom_1              Symptom_2              Symptom_3  \
0  Fungal infection     itching              skin_rash   nodal_skin_eruptions   
1  Fungal infection   skin_rash   nodal_skin_eruptions    dischromic _patches   
2  Fungal infection     itching   nodal_skin_eruptions    dischromic _patches   
3  Fungal infection     itching              skin_rash    dischromic _patches   
4  Fungal infection     itching              skin_rash   nodal_skin_eruptions   

              Symptom_4 Symptom_5 Symptom_6 Symptom_7 Symptom_8 Symptom_9  \
0   dischromic _patches       NaN       NaN       NaN       NaN       NaN   
1                   NaN       NaN       NaN       NaN       NaN       NaN   
2                   NaN       NaN       NaN       NaN       NaN       NaN   
3                   NaN       NaN       NaN       NaN       NaN       NaN   
4                   NaN       NaN       NaN       NaN       NaN       NaN   

  Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14 Symptom_15  \
0        NaN        NaN        NaN        NaN        NaN        NaN   
1        NaN        NaN        NaN        NaN        NaN        NaN   
2        NaN        NaN        NaN        NaN        NaN        NaN   
3        NaN        NaN        NaN        NaN        NaN        NaN   
4        NaN        NaN        NaN        NaN        NaN        NaN   

  Symptom_16 Symptom_17  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [134]:
li=[f'Symptom_{i}' for i in range(1,18)]
li

['Symptom_1',
 'Symptom_2',
 'Symptom_3',
 'Symptom_4',
 'Symptom_5',
 'Symptom_6',
 'Symptom_7',
 'Symptom_8',
 'Symptom_9',
 'Symptom_10',
 'Symptom_11',
 'Symptom_12',
 'Symptom_13',
 'Symptom_14',
 'Symptom_15',
 'Symptom_16',
 'Symptom_17']

In [135]:
disease_list=[]
symptom_list=[]
d=defaultdict(list)
c=1

for i,row in raw_df.iterrows():
    for j in li:
        if str(row[j])!='nan' and row['Disease']!='':
            d[row['Disease']].append(row[j])
    
    
    
    

In [136]:
for i in d:
    d[i]=list(set(d[i]))


In [137]:
for i in d:
    print(d[i])

[' nodal_skin_eruptions', 'itching', ' skin_rash', ' dischromic _patches']
[' continuous_sneezing', ' shivering', ' watering_from_eyes', ' chills']
[' acidity', ' chest_pain', ' cough', ' vomiting', ' stomach_pain', ' ulcers_on_tongue']
[' loss_of_appetite', ' abdominal_pain', ' nausea', ' yellowish_skin', ' yellowing_of_eyes', ' vomiting', 'itching']
[' spotting_ urination', ' stomach_pain', ' skin_rash', 'itching', ' burning_micturition']
[' abdominal_pain', ' loss_of_appetite', ' internal_itching', ' vomiting', ' indigestion', ' passage_of_gases']
[' muscle_wasting', ' patches_in_throat', ' extra_marital_contacts', ' high_fever']
[' restlessness', ' irregular_sugar_level', ' weight_loss', ' polyuria', ' excessive_hunger', ' lethargy', ' fatigue', ' obesity', ' increased_appetite', ' blurred_and_distorted_vision']
[' sunken_eyes', ' vomiting', ' dehydration', ' diarrhoea']
[' high_fever', ' mucoid_sputum', ' cough', ' fatigue', ' family_history', ' breathlessness']
[' dizziness', ' l

In [138]:
# Save cleaned data as CSV
f = open('new_data1.csv', 'w')
with f:
    writer = csv.writer(f)
    for key, val in d.items():
        for i in range(len(val)):
            writer.writerow([key, val[i]])


In [139]:
df = pd.read_csv('new_data1.csv',encoding="ISO-8859-1")
df.columns = ['disease', 'symptom']
df.head()

disease               symptom
0  Fungal infection               itching
1  Fungal infection             skin_rash
2  Fungal infection   dischromic _patches
3           Allergy   continuous_sneezing
4           Allergy             shivering

In [140]:
len(df)

320

In [141]:
# Remove any rows with empty values
df.replace(float('nan'), np.nan, inplace=True)
df.dropna(inplace=True)

In [142]:
from sklearn import preprocessing

In [143]:
n_unique = len(df['symptom'].unique())
n_unique

130

In [144]:
# Encode the Labels
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(df['symptom'])
integer_encoded

array([129,  98,  32,  25,  94, 120,  19,   2,  18,  26, 119, 105, 116,
        59,   0,  70, 128, 127, 119, 129, 102, 105,  98, 129,  17,   0,
        59,  51, 119,  49,  78,  68,  79,  38,  45,  90,  52, 124,  81,
        37,  58,  41,  72,  48,  13, 106, 119,  29,  31,  45,  66,  26,
        41,  39,  14,  34,  60,  18,  44,  57,  30,  37,   2, 103, 118,
        49,  44,  53,  13,  34,  60, 121,  71,   6,   4, 119,  44, 122,
         0,  45, 124,  28, 128, 119,  41, 129,  31,  70,  45, 107,  19,
        67, 119,  44,  59,  45,  63,  62,  58,  41,  98, 108, 129,  44,
        88,  59,  55,  70,  45,  62,  19,  67, 119,  41,  98,  88,  73,
        44,   6,   0,  31,  70,  45,  23, 115,  19,   7, 119,  41,  44,
        59,   0,  55,  70,  28,  31,  63, 128, 127,  67, 119,  59,   0,
        28,  85,  62, 128, 126, 127,  58,  41,  86, 129,  59,  70, 128,
       127,  39,  41,  59,   0,  55,  70,  28, 128, 127, 119,  41,  59,
         0,  55,  70,  45,  28,  21, 128, 127, 119,  41, 104,   

In [145]:
# One Hot Encode the Labels
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [146]:
len(onehot_encoded)


320

In [147]:
len(onehot_encoded[0])

130

In [148]:
cols = np.asarray(df['symptom'].unique())
cols

array(['itching', ' skin_rash', ' dischromic _patches',
       ' continuous_sneezing', ' shivering', ' watering_from_eyes',
       ' chills', ' acidity', ' chest_pain', ' cough', ' vomiting',
       ' stomach_pain', ' ulcers_on_tongue', ' loss_of_appetite',
       ' abdominal_pain', ' nausea', ' yellowish_skin',
       ' yellowing_of_eyes', ' spotting_ urination',
       ' burning_micturition', ' internal_itching', ' indigestion',
       ' passage_of_gases', ' muscle_wasting', ' patches_in_throat',
       ' extra_marital_contacts', ' high_fever', ' restlessness',
       ' irregular_sugar_level', ' weight_loss', ' polyuria',
       ' excessive_hunger', ' lethargy', ' fatigue', ' obesity',
       ' increased_appetite', ' blurred_and_distorted_vision',
       ' sunken_eyes', ' dehydration', ' diarrhoea', ' mucoid_sputum',
       ' family_history', ' breathlessness', ' dizziness',
       ' loss_of_balance', ' headache', ' lack_of_concentration',
       ' depression', ' stiff_neck', ' visua

In [149]:
# Create a new dataframe to save OHE labels
df_ohe = pd.DataFrame(columns = cols)
df_ohe.head()

Empty DataFrame
Columns: [itching,  skin_rash,  dischromic _patches,  continuous_sneezing,  shivering,  watering_from_eyes,  chills,  acidity,  chest_pain,  cough,  vomiting,  stomach_pain,  ulcers_on_tongue,  loss_of_appetite,  abdominal_pain,  nausea,  yellowish_skin,  yellowing_of_eyes,  spotting_ urination,  burning_micturition,  internal_itching,  indigestion,  passage_of_gases,  muscle_wasting,  patches_in_throat,  extra_marital_contacts,  high_fever,  restlessness,  irregular_sugar_level,  weight_loss,  polyuria,  excessive_hunger,  lethargy,  fatigue,  obesity,  increased_appetite,  blurred_and_distorted_vision,  sunken_eyes,  dehydration,  diarrhoea,  mucoid_sputum,  family_history,  breathlessness,  dizziness,  loss_of_balance,  headache,  lack_of_concentration,  depression,  stiff_neck,  visual_disturbances,  irritability,  weakness_in_limbs,  neck_pain,  back_pain,  altered_sensorium,  weakness_of_one_body_side,  dark_urine,  sweating,  muscle_pain,  mild_fever,  malaise,  swelled_lymph_nodes,  red_spots_over_body,  joint_pain,  pain_behind_the_eyes,  constipation,  toxic_look_(typhos),  belly_pain,  receiving_blood_transfusion,  yellow_urine,  receiving_unsterile_injections,  coma,  stomach_bleeding,  acute_liver_failure,  swelling_of_stomach,  fluid_overload,  history_of_alcohol_consumption,  distention_of_abdomen,  phlegm,  blood_in_sputum,  congestion,  loss_of_smell,  throat_irritation,  runny_nose,  redness_of_eyes,  sinus_pressure,  rusty_sputum,  fast_heart_rate,  pain_during_bowel_movements,  bloody_stool,  pain_in_anal_region,  irritation_in_anus,  swollen_legs,  bruising,  cramps,  swollen_blood_vessels,  prominent_veins_on_calf,  puffy_face_and_eyes,  enlarged_thyroid,  abnormal_menstruation, ...]
Index: []

[0 rows x 130 columns]

In [150]:
for i in range(len(onehot_encoded)):
    df_ohe.loc[i] = onehot_encoded[i]

In [151]:
df_ohe.head()

itching   skin_rash   dischromic _patches   continuous_sneezing  \
0      0.0         0.0                   0.0                   0.0   
1      0.0         0.0                   0.0                   0.0   
2      0.0         0.0                   0.0                   0.0   
3      0.0         0.0                   0.0                   0.0   
4      0.0         0.0                   0.0                   0.0   

    shivering   watering_from_eyes   chills   acidity   chest_pain   cough  \
0         0.0                  0.0      0.0       0.0          0.0     0.0   
1         0.0                  0.0      0.0       0.0          0.0     0.0   
2         0.0                  0.0      0.0       0.0          0.0     0.0   
3         0.0                  0.0      0.0       0.0          0.0     0.0   
4         0.0                  0.0      0.0       0.0          0.0     0.0   

   ...   foul_smell_of urine   continuous_feel_of_urine   bladder_discomfort  \
0  ...                   0.0                        0.0                  0.0   
1  ...                   0.0                        0.0                  0.0   
2  ...                   0.0                        0.0                  0.0   
3  ...                   0.0                        0.0                  0.0   
4  ...                   0.0                        0.0                  0.0   

    silver_like_dusting   small_dents_in_nails   inflammatory_nails  \
0                   0.0                    0.0                  0.0   
1                   0.0                    0.0                  0.0   
2                   0.0                    0.0                  0.0   
3                   0.0                    0.0                  0.0   
4                   0.0                    0.0                  0.0   

    skin_peeling   blister   yellow_crust_ooze   red_sore_around_nose  
0            0.0       0.0                 0.0                    1.0  
1            0.0       0.0                 0.0                    0.0  
2            0.0       0.0                 0.0                    0.0  
3            0.0       0.0                 0.0                    0.0  
4            0.0       0.0                 0.0                    0.0  

[5 rows x 130 columns]

In [152]:
len(df_ohe)

320

In [153]:
# Disease Dataframe
df_disease = df['disease']
df_disease.head()

0    Fungal infection
1    Fungal infection
2    Fungal infection
3             Allergy
4             Allergy
Name: disease, dtype: object

In [154]:
# Concatenate OHE Labels with the Disease Column
df_concat = pd.concat([df_disease,df_ohe], axis=1)
df_concat.head()

disease  itching   skin_rash   dischromic _patches  \
0  Fungal infection      0.0         0.0                   0.0   
1  Fungal infection      0.0         0.0                   0.0   
2  Fungal infection      0.0         0.0                   0.0   
3           Allergy      0.0         0.0                   0.0   
4           Allergy      0.0         0.0                   0.0   

    continuous_sneezing   shivering   watering_from_eyes   chills   acidity  \
0                   0.0         0.0                  0.0      0.0       0.0   
1                   0.0         0.0                  0.0      0.0       0.0   
2                   0.0         0.0                  0.0      0.0       0.0   
3                   0.0         0.0                  0.0      0.0       0.0   
4                   0.0         0.0                  0.0      0.0       0.0   

    chest_pain  ...   foul_smell_of urine   continuous_feel_of_urine  \
0          0.0  ...                   0.0                        0.0   
1          0.0  ...                   0.0                        0.0   
2          0.0  ...                   0.0                        0.0   
3          0.0  ...                   0.0                        0.0   
4          0.0  ...                   0.0                        0.0   

    bladder_discomfort   silver_like_dusting   small_dents_in_nails  \
0                  0.0                   0.0                    0.0   
1                  0.0                   0.0                    0.0   
2                  0.0                   0.0                    0.0   
3                  0.0                   0.0                    0.0   
4                  0.0                   0.0                    0.0   

    inflammatory_nails   skin_peeling   blister   yellow_crust_ooze  \
0                  0.0            0.0       0.0                 0.0   
1                  0.0            0.0       0.0                 0.0   
2                  0.0            0.0       0.0                 0.0   
3                  0.0            0.0       0.0                 0.0   
4                  0.0            0.0       0.0                 0.0   

    red_sore_around_nose  
0                    1.0  
1                    0.0  
2                    0.0  
3                    0.0  
4                    0.0  

[5 rows x 131 columns]

In [155]:
df_concat.drop_duplicates(keep='last',inplace=True)

In [156]:
len(df_concat)

320

In [157]:
# Since, every disease has multiple symptoms, combine all symptoms per disease per row
df_concat = df_concat.groupby('disease').sum()
df_concat = df_concat.reset_index()
df_concat[:100]

disease  itching   skin_rash  \
0   (vertigo) Paroymsal  Positional Vertigo      0.0         0.0   
1                                      AIDS      0.0         0.0   
2                                      Acne      0.0         0.0   
3                       Alcoholic hepatitis      1.0         0.0   
4                                   Allergy      0.0         0.0   
5                                 Arthritis      0.0         0.0   
6                          Bronchial Asthma      0.0         0.0   
7                      Cervical spondylosis      0.0         0.0   
8                               Chicken pox      0.0         0.0   
9                       Chronic cholestasis      1.0         0.0   
10                              Common Cold      0.0         0.0   
11                                   Dengue      0.0         0.0   
12                                Diabetes       0.0         0.0   
13             Dimorphic hemmorhoids(piles)      0.0         0.0   
14                            Drug Reaction      0.0         0.0   
15                         Fungal infection      0.0         0.0   
16                                     GERD      0.0         0.0   
17                          Gastroenteritis      0.0         0.0   
18                             Heart attack      0.0         0.0   
19                              Hepatitis B      1.0         0.0   
20                              Hepatitis C      0.0         0.0   
21                              Hepatitis D      1.0         0.0   
22                              Hepatitis E      1.0         0.0   
23                            Hypertension       0.0         0.0   
24                          Hyperthyroidism      0.0         1.0   
25                             Hypoglycemia      0.0         0.0   
26                           Hypothyroidism      0.0         1.0   
27                                 Impetigo      0.0         0.0   
28                                 Jaundice      1.0         0.0   
29                                  Malaria      0.0         0.0   
30                                 Migraine      0.0         0.0   
31                          Osteoarthristis      0.0         0.0   
32             Paralysis (brain hemorrhage)      0.0         0.0   
33                      Peptic ulcer diseae      1.0         0.0   
34                                Pneumonia      0.0         0.0   
35                                Psoriasis      0.0         0.0   
36                             Tuberculosis      0.0         0.0   
37                                  Typhoid      1.0         0.0   
38                  Urinary tract infection      0.0         0.0   
39                           Varicose veins      0.0         0.0   
40                              hepatitis A      1.0         0.0   

     dischromic _patches   continuous_sneezing   shivering  \
0                    0.0                   0.0         0.0   
1                    0.0                   0.0         0.0   
2                    0.0                   0.0         0.0   
3                    0.0                   0.0         0.0   
4                    0.0                   0.0         0.0   
5                    0.0                   0.0         0.0   
6                    0.0                   0.0         0.0   
7                    0.0                   0.0         0.0   
8                    0.0                   0.0         0.0   
9                    0.0                   0.0         0.0   
10                   0.0                   0.0         0.0   
11                   0.0                   0.0         0.0   
12                   0.0                   0.0         0.0   
13                   0.0                   0.0         0.0   
14                   0.0                   0.0         0.0   
15                   0.0                   0.0         0.0   
16                   1.0                   0.0         0.0   
17                   0.0                   0.0         0.0   
1

In [158]:
len(df_concat)

41

In [159]:
df_concat.to_csv("training_dataset1.csv", index=False)

In [160]:
# One Hot Encoded Features
X = df_concat.iloc[:,1:]

# Labels
y = df_concat['disease']

## Model Training

In [161]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier

In [162]:
# Train Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [163]:
len(X_train), len(y_train)

(32, 32)

In [164]:
len(X_test), len(y_test)

(9, 9)

In [165]:
dt = DecisionTreeClassifier()
clf_dt=dt.fit(X, y)

In [104]:
clf_dt.score(X, y)

1.0

In [108]:
disease_pred = clf_dt.predict(X)

In [109]:
disease_pred

array(['(vertigo) Paroymsal  Positional Vertigo', 'AIDS', 'Acne',
       'Alcoholic hepatitis', 'Allergy', 'Arthritis', 'Bronchial Asthma',
       'Cervical spondylosis', 'Chicken pox', 'Chronic cholestasis',
       'Common Cold', 'Dengue', 'Diabetes ',
       'Dimorphic hemmorhoids(piles)', 'Drug Reaction',
       'Fungal infection', 'GERD', 'Gastroenteritis', 'Heart attack',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Hypertension ', 'Hyperthyroidism', 'Hypoglycemia',
       'Hypothyroidism', 'Impetigo', 'Jaundice', 'Malaria', 'Migraine',
       'Osteoarthristis', 'Paralysis (brain hemorrhage)',
       'Peptic ulcer diseae', 'Pneumonia', 'Psoriasis', 'Tuberculosis',
       'Typhoid', 'Urinary tract infection', 'Varicose veins',
       'hepatitis A'], dtype=object)

# Using Support Vector Machine

In [126]:

from sklearn.svm import SVC
from sklearn.svm import LinearSVC

In [166]:
len(X)

41

In [172]:
p=[]
for i in range(130):
    if i%2==0:
        p.append(1)
    else:
        p.append(0)

In [173]:
SVM_init = SVC()
model_SVM_init = SVM_init.fit(X, y)

In [174]:
model_SVM_init.score(X_test,y_test)

1.0

In [175]:
model_SVM_init.predict([p])


array(['Pneumonia'], dtype=object)

In [176]:
clf_dt.predict([p])

array(['Common Cold'], dtype=object)

In [177]:
from sklearn.ensemble import RandomForestClassifier
rnd_forest = RandomForestClassifier()
rnd_forest.fit(X_train,y_train)

RandomForestClassifier()

In [179]:
from sklearn.metrics import accuracy_score
y_pred = rnd_forest.predict(X_test)
accuracy_score(y_test,y_pred)

0.0