In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
df=pd.read_csv('homeprices.csv')

In [3]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [4]:
# price(y) we want
# so equation for the above will become like price=y=m1*area+m2*bedrooms+m3*age+b(y=m1x1+m2x2+m3x3)
# area,bedrooms,age->independent variable(features)
# price->dependent variable
# m1,m2,m3,age->coefficients
# b->intercept

In [5]:
#handling Nan in bedrooms
#math floor is used for round of purpose

In [6]:
import math
median=math.floor(df['bedrooms'].median())
median

4

In [7]:
df['bedrooms'].fillna(median,inplace=True) ##taking care of missing data

In [8]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [9]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df['price']) #TrAIN MODEl

LinearRegression()

In [10]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [11]:
reg.intercept_

221323.00186540408

In [12]:
reg.predict([[3000,3,40]])

array([498408.25158031])

In [25]:
reg.predict([[4500,7,50]])#(112.06244194*4500+23388.88007794*7+ 50*-3231.71790863+221323.00186540408)

array([727740.25571894])