# NumPy Operations

<ul>
    <li><b style='font-size :2em'>Array with Array</b></li>
    <li><b>Array with Scalars</b></li>
    <li><b>Universal Array Functions</b></li>
 </ul>   

In [2]:
import numpy as np

In [3]:
arr=np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
arr+10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [7]:
arr/arr

<ipython-input-7-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [8]:
arr=np.arange(2,40,2)


In [9]:
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [10]:
2/arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ,
       0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667,
       0.0625    , 0.05882353, 0.05555556, 0.05263158])

In [11]:
arr/2

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19.])

In [12]:
arr**2

array([   4,   16,   36,   64,  100,  144,  196,  256,  324,  400,  484,
        576,  676,  784,  900, 1024, 1156, 1296, 1444], dtype=int32)

In [13]:
np.sqrt(arr)

array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766,
       3.46410162, 3.74165739, 4.        , 4.24264069, 4.47213595,
       4.69041576, 4.89897949, 5.09901951, 5.29150262, 5.47722558,
       5.65685425, 5.83095189, 6.        , 6.164414  ])

In [14]:
np.max(arr)

38

In [15]:
np.sin(arr)

array([ 0.90929743, -0.7568025 , -0.2794155 ,  0.98935825, -0.54402111,
       -0.53657292,  0.99060736, -0.28790332, -0.75098725,  0.91294525,
       -0.00885131, -0.90557836,  0.76255845,  0.27090579, -0.98803162,
        0.55142668,  0.52908269, -0.99177885,  0.29636858])

In [16]:
np.cos(arr)

array([-0.41614684, -0.65364362,  0.96017029, -0.14550003, -0.83907153,
        0.84385396,  0.13673722, -0.95765948,  0.66031671,  0.40808206,
       -0.99996083,  0.42417901,  0.64691932, -0.96260587,  0.15425145,
        0.83422336, -0.84857027, -0.12796369,  0.95507364])

In [17]:
np.exp(arr)

array([7.38905610e+00, 5.45981500e+01, 4.03428793e+02, 2.98095799e+03,
       2.20264658e+04, 1.62754791e+05, 1.20260428e+06, 8.88611052e+06,
       6.56599691e+07, 4.85165195e+08, 3.58491285e+09, 2.64891221e+10,
       1.95729609e+11, 1.44625706e+12, 1.06864746e+13, 7.89629602e+13,
       5.83461743e+14, 4.31123155e+15, 3.18559318e+16])

In [25]:
arr=np.array([30*22/180*7,45,60,90])

In [26]:
np.sin(arr)

array([ 0.50891633,  0.85090352, -0.30481062,  0.89399666])