# NUMPY ARRAYS

In [1]:
a=[1,2]
x,y=a

In [2]:
x='1 2 3'.split(' ')
x

['1', '2', '3']

In [3]:
mylist=[1,2,3]


In [4]:
import numpy as np
np.array(mylist) #casting to 1 d array

array([1, 2, 3])

In [6]:
print('enter row and col of matrix')
a,b=[int(i) for i in input().split(' ')]
print(type(a))
print(b)

enter row and col of matrix
3 2
<class 'int'>
2


In [7]:
arr= np.array(mylist)
print(arr)

[1 2 3]


In [8]:
arr


array([1, 2, 3])

In [9]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [10]:
np.array(my_mat) #casting to 2 d array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,11,2)


array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [17]:
np.linspace(0,2,2)

array([0., 2.])

In [18]:
np.linspace(0,2,10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.random.randn(1)

array([-0.44541482])

In [21]:
np.random.randint(0,100,10)

array([23, 75,  9, 24, 18, 33, 17, 49, 21, 91])

In [22]:
np.random.randint(0,10,5)

array([3, 6, 0, 4, 7])

In [23]:
arr=np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
randomarr=np.random.randint(0,50,10)
randomarr

array([25,  9, 38, 34,  0, 18, 33, 39, 35, 37])

In [25]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:

randomarr.max()

39

In [27]:
randomarr.min()

0

In [28]:
randomarr.argmax()

7

In [29]:
randomarr.argmin()

4

In [30]:
mylist=np.array([1,2,3,4])


In [31]:
mylist.shape

(4,)

In [41]:
#important
y = np.zeros((1,3,10))#(count of sub matrix,row,columns)

In [42]:
y

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [43]:
mylist=np.arange(4)

In [44]:
mylist=mylist.reshape(2,2)

In [45]:
mylist.shape

(2, 2)

In [46]:
arr=np.arange(1,5)
arr

array([1, 2, 3, 4])

In [38]:
arr.dtype

dtype('int32')

# END 