# NumPy Indexing and Selection

In [32]:
import numpy as np

In [33]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
arr[8]

8

In [35]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [36]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [37]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [38]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [39]:
slice_of_arr=arr[0:6]
slice_of_arr[:]=100
slice_of_arr

array([100, 100, 100, 100, 100, 100])

In [40]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

INoder to avoid this we can do like this

In [41]:
arr_copy=arr.copy()


In [42]:
arr_copy

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [43]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [44]:
arr_copy[3:6]=999

In [45]:
arr_copy

array([100, 100, 100, 999, 999, 999,   6,   7,   8,   9,  10])

In [46]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [47]:
arr=np.arange(0,11)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
arr1=arr.copy()

In [56]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
slice_of_arr=arr1[0:6]

In [52]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [53]:
slice_of_arr[:]=99

In [57]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [59]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
s='hello'
print(s[-1:-3:-1])

ol
